version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
    configs:
      - source: prometheus
        target: /etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml


volumes:
  prometheus-data:

configs:
  prometheus:
    external: true
    name: prometheus
